### ISSUE TITLE
TDD on Conditions

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#10]
**Background**   
It's a good start to learn some java Conditions.

**How**   
Write ConditionTest unit tests,
includes conditions
```
Less than: a < b
Less than or equal to: a <= b
Greater than: a > b
Greater than or equal to: a >= b
Equal to a == b
Not Equal to: a != b
```

**DoD**     
All the unittests include all the conditions mentioned above

**Comment by AbhishekTiwari07** [comment]
how can i help you with this issue

**Comment by mcruzdev** [comment]
Can you assign this to me?

**Comment by fengyuanyang** [comment]
Sure, @mcruzdev
