### ISSUE TITLE
[Algorithm] Interpolation Search

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#109]
**Description**

Provide a function that implements **Interpolation Search**

```
// The idea of formula is to return higher value of pos
// when element to be searched is closer to arr[hi]. And
// smaller value when closer to arr[lo]
pos = lo + [ (x-arr[lo])*(hi-lo) / (arr[hi]-arr[Lo]) ]

arr[] ==> Array where elements need to be searched
x     ==> Element to be searched
lo    ==> Starting index in arr[]
hi    ==> Ending index in arr[]
```
**Algorithm**
Rest of the Interpolation algorithm is the same except the above partition logic.

- Step1: In a loop, calculate the value of “pos” using the probe position formula.
- Step2: If it is a match, return the index of the item, and exit.
- Step3: If the item is less than arr[pos], calculate the probe position of the left sub-array. Otherwise calculate the same in the right sub-array.
- Step4: Repeat until a match is found or the sub-array reduces to zero.

```
Given 2 parameters (int[] array, int searchNumber)
When array = {10, 12, 13, 16, 18, 19, 20, 21, 22, 23, 24, 33, 35, 42, 47}
And searchNumber = 18
Expect 4 return

When array = {10, 12, 13, 16, 18, 19, 20, 21, 22, 23, 24, 33, 35, 42, 47}
And searchNumber = 1
Expect -1 return

When array = {10, 9}
And searchNumber = 1
Expect illegalArgumentException throw

```
**Additional context**

Add any other context, links references or screenshots about the feature request here.

**Important Checklist**
- [ ] I have written unit test first, make it red(fail first).
- [ ] I have then written logic code, make it green(success)
- [ ] I have tried to refactor my code, make it understandable(document my code)

**Comment by ldrf** [comment]
Hi! can I work in this?
Another question, can i supposed that array will always sorted?

**Comment by fengyuanyang** [comment]
Hi @ldrf 
Sure, 
if the array is not sorted, please throw illegalArgument exception
