### ISSUE TITLE
[Algorithm] Ternary Search

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#116]
**Description**
Provide a function that implements **Ternary Search**

Similar to binary search where we divide the array into two parts but in this algorithm, we divide the given array into three parts and determine which has the key (searched element)

```
// We can divide the array into three parts by taking mid1 and mid2 which can be calculated as shown below. Initially, l and r will be equal to 0 and n-1 respectively, where n is the length of the array. 

mid1 = l + (r-l)/3 
mid2 = r – (r-l)/3 

```
**Algorithm**
Steps to perform Ternary Search: 

- First, we compare the key with the element at mid1. If found equal, we return mid1.
- If not, then we compare the key with the element at mid2. If found equal, we return mid2.
- If not, then we check whether the key is less than the element at mid1. If yes, then recur to the first part.
- If not, then we check whether the key is greater than the element at mid2. If yes, then recur to the third part.
- If not, then we recur to the second (middle) part.

```
Given 2 parameters (int[] array, int searchNumber)
When array = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 }
And searchNumber = 8
Expect 7 return

When array = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 }
And searchNumber = 11
Expect -1 return

When array = {10, 9}
And searchNumber = 1
Expect illegalArgumentException throw ( not sorted)

```
**Additional context**

Add any other context, links references or screenshots about the feature request here.

**Important Checklist**
- [ ] I have written unit test first, make it red(fail first).
- [ ] I have then written logic code, make it green(success)
- [ ] I have tried to refactor my code, make it understandable(document my code)

**Comment by singloon** [comment]
Hi @fengyuanyang can I get this issue assigned to me?

**Comment by fengyuanyang** [comment]
Sure, @singloon

**Comment by singloon** [comment]
Please can you review my PR @fengyuanyang

**Comment by fengyuanyang** [comment]
Hi @singloon 
I have left some comments on this PR

**Comment by singloon** [comment]
Hi @fengyuanyang I don’t see any comments on the PR.

**Comment by singloon** [comment]
Can you please add the comments to the PR, so I know what needs to change. Referencing the code? As part the refactoring I changed from recursion to iteration as it is faster and uses less memory (stack) for Java.

**Comment by fengyuanyang** [comment]
I don't know why , but i did leave comments there 
![image](https://user-images.githubusercontent.com/3124499/97284564-26bf1380-187c-11eb-9a8e-9ab6b086af26.png)

**Comment by singloon** [comment]
Hi @fengyuanyang, from the screenshot I can see that the comment is pending. So it’s only visible to you.

**Comment by singloon** [comment]
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/reviewing-proposed-changes-in-a-pull-request

**Comment by fengyuanyang** [comment]
Hi @singloon 
sorry , you are right !! I didn't know how this works!! Thanks for addressing this issue 
Now it should be visible to you
