### ISSUE TITLE
TDD on Statements

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#12]
**Background**
It's a good start to learn some java Statements.

**How**
Write StatementsTest unit tests,
includes statements
```
if
else if
else 
switch 
```
**DoD**
All the unittests include all the statements mentioned above

**Comment by DeepaliKalagate** [comment]
I am interested to do this. Please assign to me

**Comment by fengyuanyang** [comment]
Assigned 
Thanks @DeepaliKalagate

**Comment by MERCUROUS** [comment]
please merge it has not added in my hactoberfest PR
