### ISSUE TITLE
TDD on For Loops

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#14]
**Background**
It's a good start to learn some java For Loops.

**How**
Write ForLoopTest unit tests,
includes

```
for (statement 1; statement 2; statement 3) 
for each loop :
for (type variableName : arrayName) 
```
**DoD**
All the unittests include all the statements mentioned above

**Comment by Shweta200126** [comment]
Can you explain a little more ...

**Comment by fengyuanyang** [comment]
Hi @Shweta200126 
Thanks for asking . 
There are two types of for loops 

1. Java For loop 
2. For-each loop

You could create some unit tests first such as 

**For Java For Loop**
```
1. 
Given 2 parameters (start, end)
When start = 0, end = 12
Expect execute 12 times 
And Return 12;
ex. for ( int i=start;i<end;i++)

2. 
Given 3 parameters (start, end, plus)
When start = 0, end = 12, plus=2
Expect execute x times 
And Return x;
ex. for ( int i=start;i<=end;i=i+plus)

... others you can imagine on your mind.
```

**For Java For-Each Loop**
```
1. 
Given 1 parameters (String Array)
When Array Size is 12
Expect execute 12 times 
And Return 12;
ex. for (String str: strArray).

2. 
Given 1 parameter (int Array)
When Array Size is 12
Expect sum all the integer values 
And Return SUM

```

**Comment by btirumala1219** [comment]
I can take a look at this

**Comment by fengyuanyang** [comment]
Thanks @btirumala1219 
I have assigned to you

**Comment by btirumala1219** [comment]
https://github.com/fengyuanyang/JavaTDD/pull/19

**Comment by btirumala1219** [comment]
lmk if anything else you can assign
