### ISSUE TITLE
Need to check code style in ci-flow

### ISSUE THREAD

**Issue by liun03** [fengyuanyang/JavaTDD#24]
Suggestion code style: [google java code style](https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml) 
How to: https://docs.gradle.org/current/userguide/checkstyle_plugin.html

**Comment by januslinhc** [comment]
I would like to work on this issue @liun03

**Comment by januslinhc** [comment]
@liun03 done. Please merge @fengyuanyang
