### ISSUE TITLE
TDD for switch

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#27]
**Description**
Unit tests for Switch

Test cases below
```
1. 
Given a enum parameter (**SUNDAY, MONDAY to SATURDAY**)
When enum is SUNDAY
Expect" SUNDAY" return

When enum is null
Expect illegalArgumentException throw

2. 
Given a int parameter (0,1,2,3,4,5,6)
When parameter is 2
Expect "TUESDAY" return

When parameter is 6
Expect "SATURDAY" return

When parameter is 7
Expect illegalArgumentException throw


3. 
Given a String parameter ("0","1","2","3","4","5","6")
When parameter is "2"
Expect "TUESDAY" return
When parameter is "6"
Expect "TUESDAY" return

When parameter is "7"
Expect illegalArgumentException throw

```
**Additional context**
Add any other context, links references or screenshots about the feature request here.

**Important Checklist** 
-   [ ] I have written unit test first, make it red(fail first).
-   [ ] I have then written logic code, make it green(success)
-   [ ] I have tried to refactor my code, make it understandable(document my code)

**Comment by mcruzdev** [comment]
Assign to me @fengyuanyang, please ;)

**Comment by sahaparamjit** [comment]
can you assign to me ?

**Comment by fengyuanyang** [comment]
Hi @sahaparamjit 
Sure, go ahead and code it !

**Comment by fengyuanyang** [comment]
Hi @mcruzdev 
I would like to give others a try since you are pretty good in other issues.
BTW, you are welcome to create issues here , with some TDD cases , anything on you mind is welcome

**Comment by fengyuanyang** [comment]
hi @sahaparamjit  are you still working on it ? otherwise , i will assign to others

**Comment by farzado** [comment]
Can you assign this to me pls @fengyuanyang?
