### ISSUE TITLE
Test Coverage required

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#31]
**Briefly** 
As a developer, I would like to know how is the coverage number of these TDD codes

Any Suggestion is welcome

**Comment by ipapast** [comment]
Added proposed tool for that purpose with [PR 36](https://github.com/fengyuanyang/JavaTDD/pull/36). This is Jacoco, the most used and up to date tool for Java currently.

**Comment by fengyuanyang** [comment]
Thanks @ipapast 
Now we are able to make sure the coverage rate is over 90 % 👍
