### ISSUE TITLE
TDD for calculator object

### ISSUE THREAD

**Issue by mcruzdev** [fengyuanyang/JavaTDD#32]
We need to a calculator object, **without to use static method**

To create a calculator with the operations ( +, -, *, / )

10 + 10 = 20
15 - 10 = 5
10 * 1 = 10;
8 / 2 = 4;
10 / 0 -> In this case you can use `Assertions.assertThatThrownBy` because the operation by zero throws a ArithmeticException 
```
Assertions.assertThatThrownBy(() -> {
            // Use the method calculator to divide here 
            // calculator.divide(10, 0)
        }).isInstanceOf(ArithmeticException.class);

```

**Comment by mcruzdev** [comment]
@fengyuanyang can you add label or a suggestion for this issue?

**Comment by btirumala1219** [comment]
Working on this

**Comment by btirumala1219** [comment]
https://github.com/fengyuanyang/JavaTDD/pull/37

**Comment by fengyuanyang** [comment]
I think 
```
Assertions.assertThrows(ArithmeticException.class, () -> {
   calculator.divide(10, 0);
  });
```
might be more clear for the code should be same as 
```
Assertions.assertThatThrownBy(() -> {
            // Use the method calculator to divide here 
            // calculator.divide(10, 0)
        }).isInstanceOf(ArithmeticException.class);
```

**Comment by btirumala1219** [comment]
@fengyuanyang Updated

**Comment by btirumala1219** [comment]
PR has been updated
