### ISSUE TITLE
TDD for Break And Continue(While loop) 

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#46]
**Description**
Unit tests for Break and Continue
Include For loop

Test cases below
```
While LOOP(Break)

Given 1 int parameter for loops (break)
And there is a counter to count the execution times
And loop should execute 10 times at most

When break = 7
Expect counter is 7 and return

When break = 0
Expect counter is 0 and return

When break = 10
Expect counter is 10 and return

When break = -1
Expect counter is 10 and return

==========================
While LOOP(Continue)
Given 1 int parameter for loops (continue)
And there is a counter to count the execution times
And loop should execute 10 times at most

When continue = 7
Expect counter is 9 and return

When continue = 0
Expect counter is 9 and return

When continue = 10
Expect counter is 10 and return

When continue = -1
Expect counter is 10 and return

```
**Additional context**
Add any other context, links references or screenshots about the feature request here.

**Important Checklist** 
-   [ ] I have written unit test first, make it red(fail first).
-   [ ] I have then written logic code, make it green(success)
-   [ ] I have tried to refactor my code, make it understandable(document my code)

**Comment by januslinhc** [comment]
Hi @fengyuanyang i would like to work on this issue

**Comment by fengyuanyang** [comment]
@januslinhc  Sure 👍

**Comment by januslinhc** [comment]
hi @fengyuanyang 
for the while loop break,
may i know why if we break the loop at 10 it should return 10 while if we break the loop at 7 it should return 6??

**Comment by fengyuanyang** [comment]
good question! it's my bad, i didn't put the number right ! i fix it .

**Comment by fengyuanyang** [comment]
it should be "continue" not break , typo
sorry

**Comment by fengyuanyang** [comment]
Hi @januslinhc 
sorry , it's not easy to make sample logical all correct.
I will start to get some better practice from kata.
