### ISSUE TITLE
[Design Pattern] Factory Pattern - Car 

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#52]
**Description**
Everyone is welcome to take this issue, enjoy TDD with design pattern

Let get start with design patten !
`Factory Pattern`
If you have no idea Factory Pattern is 
Check [here](https://levelup.gitconnected.com/learn-the-factory-pattern-in-a-clean-simple-animal-application-35fa23aa40e2)

package at
`com.ordestiny.tdd.designpattern.factorypattern`
```
Given A factory Object(CarFactory)
And a Car Enum (BENZ, BMW, TOYOTA, JAGUR, ....so on)
And corresponding Car Object (should extend from Car)

When ask factory to create TOYOTA
Expect Car(Toyota) return 
And it is from "JAPAN" 

When ask factory to create BMW
Expect Car(BMW) return 
And it is from "GERMANY"

When ask factory to create BENZ
Expect Car(BENZ) return 
And it is from "GERMANY"

When ask factory to create OTHERS
Expect exception throw

(you can imagine more if you like
```
**Additional context**

Add any other context, links references or screenshots about the feature request here.

**Important Checklist**
- [ ] I have written unit test first, make it red(fail first).
- [ ] I have then written logic code, make it green(success)
- [ ] I have tried to refactor my code, make it understandable(document my code)

**Comment by frosse** [comment]
Hi, could you please assign this to me?

**Comment by fengyuanyang** [comment]
sure, @frosse 
enjoy it 👍
