### ISSUE TITLE
[TDD] Kata - integer range contains

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#54]
**Description**
There are some interesting samples to play with TDD - [Kata-Range](https://codingdojo.org/kata/Range/)

Try to play with `integer ranger contains`

**original requirements**
```
[2,6) contains {2,4}
[2,6) doesn’t contain {-1,1,6,10}
```

For java
```
Given 3 parameters for rangeContainsAll(start, end, compareArray) includes start and end
When start = 2, end = 6
And compareArray = {2,4}
Expect return true

When start = 2, end = 6
And compareArray = {2,4,7}
Expect return false

When start = 2, end = 6
And compareArray = {-1,1,6,10}
Expect return false

When start = 6, end =26
Expect throw illegalArgumentException
```
**Additional context**

Add any other context, links references or screenshots about the feature request here.

**Important Checklist**
- [ ] I have written unit test first, make it red(fail first).
- [ ] I have then written logic code, make it green(success)
- [ ] I have tried to refactor my code, make it understandable(document my code)

**Comment by ramonborges15** [comment]
@fengyuanyang can you assigned it to me?

**Comment by fengyuanyang** [comment]
sure, @ramonborges15 
assigned
