### ISSUE TITLE
[TDD] Kata - getAllPoints

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#56]
**Description**
There are some interesting samples to play with TDD - [Kata-Range](https://codingdojo.org/kata/Range/)

Try to play with `get All points`
This one should be good start for someone just get started on TDD.

**original requirements**
```
[2,6) allPoints = {2,3,4,5}
```

For java
```
Given 2 parameters for getAllPoints(start, end) includes start and end
When start = 2, end = 6
Expect return array{2,3,4,5,6}

When start = 4, end = 2
Expect return illegalArgumentException

When start = 4, end =4
Expect return array {4}
```
**Additional context**

Add any other context, links references or screenshots about the feature request here.

**Important Checklist**
- [ ] I have written unit test first, make it red(fail first).
- [ ] I have then written logic code, make it green(success)
- [ ] I have tried to refactor my code, make it understandable(document my code)

**Comment by hgky95** [comment]
Hi @fengyuanyang 
I'm so excited about this one, please assign it to me. Thank you!

**Comment by fengyuanyang** [comment]
Sure @hgky95  , assigned
