### ISSUE TITLE
[TDD] Kata - ContainsRange

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#57]
**Description**
There are some interesting samples to play with TDD - [Kata-Range](https://codingdojo.org/kata/Range/)

Lets play with `ContainsRange `

**original requirements**
```
[2,5) doesn’t contain [7,10)
[2,5) doesn’t contain [3,10)
[3,5) doesn’t contain [2,10)
[2,10) contains [3,5]
[3,5] contains [3,5)
```

For java
```
Given 4 parameters for containsRange(start, end, compareStart, compareEnd)
When arguments are (2,5,   7,10)
Expect return false

When arguments are (2,5,   3,10)
Expect return false

When arguments are (3,5,   2,10)
Expect return false

When arguments are (2,10,   3,5)
Expect return true

When arguments are (3,5,   3,5)
Expect return true

When arguments are (5,3,   3,5)
Expect throw illegalArgumentException

When arguments are (3,5,   5,3)
Expect throw illegalArgumentException
```
**Additional context**

Add any other context, links references or screenshots about the feature request here.

**Important Checklist**
- [ ] I have written unit test first, make it red(fail first).
- [ ] I have then written logic code, make it green(success)
- [ ] I have tried to refactor my code, make it understandable(document my code)

**Comment by snjazim** [comment]
Please assign this to me.
