### ISSUE TITLE
[TDD] Kata - overlapsRange

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#58]
**Description**
There are some interesting samples to play with TDD - [Kata-Range](https://codingdojo.org/kata/Range/)

Lets play with `overlapsRange `

**original requirements**
```
[2,5) doesn’t overlap with [7,10)
[2,10) overlaps with [3,5)
[3,5) overlaps with [3,5)
[2,5) overlaps with [3,10)
[3,5) overlaps with [2,10)
```

For java
```
Given 4 parameters for containsRange(start, end, compareStart, compareEnd)
When arguments are (2,5,   7,10)
Expect return false

When arguments are (2,10,   3,5)
Expect return true

When arguments are (3,5,   3,5)
Expect return true

When arguments are (2,5,   3,10)
Expect return true

When arguments are (3,5,   2,10)
Expect return true

When arguments are (5,3,   3,5)
Expect throw illegalArgumentException

When arguments are (3,5,   5,3)
Expect throw illegalArgumentException
```
**Additional context**

Add any other context, links references or screenshots about the feature request here.

**Important Checklist**
- [ ] I have written unit test first, make it red(fail first).
- [ ] I have then written logic code, make it green(success)
- [ ] I have tried to refactor my code, make it understandable(document my code)

**Comment by snjazim** [comment]
Please assign this to me.

**Comment by snjazim** [comment]
Hi, @fengyuanyang, I don't have the access to create PR for this repo.   
```
remote: Permission to fengyuanyang/JavaTDD.git denied to snjazim.
fatal: unable to access 'https://github.com/fengyuanyang/JavaTDD.git/': The requested URL returned error: 403
```

**Comment by fengyuanyang** [comment]
Hi @snjazim 
You may have a look on this video for first pr for beginner(on open source)

https://hacktoberfest.digitalocean.com/details

You should create a branch on your own repo and request a pr

**Comment by fengyuanyang** [comment]
pr merged
