### ISSUE TITLE
[TDD] Kata - Diamond

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#66]
**Description**
The requirement for this issue is to print a diamond
[Kata-Dimond](https://codingdojo.org/kata/Diamond/)

you can follow this reference to enjoy TDD. Fail-> Pass -> Fail -> Pass
[Reference](http://claysnow.co.uk/recycling-tests-in-tdd/) 

We would like to make it simpler to check its repeat characters.
```
Given 1 parameters (cahr)
When char = 'A'
Expect output
 A

When char = 'B'
Expect output
 ABBA

When char = 'C'
Expect 
 ABBCCCBBA

When char = 'D'
Expect 
 ABBCCCDDDDCCCBBA

.....  so on , should fit From 'A' to 'Z'

When char = '1'
Expect throw IllegalArgumentExcpetion\



```
**Additional context**

Add any other context, links references or screenshots about the feature request here.

**Important Checklist**
- [ ] I have written unit test first, make it red(fail first).
- [ ] I have then written logic code, make it green(success)
- [ ] I have tried to refactor my code, make it understandable(document my code)

**Comment by farzado** [comment]
Can you assign this to me pls?

**Comment by fengyuanyang** [comment]
sure
