### ISSUE TITLE
[TDD] Kata - Number -> Roman Numerals

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#71]
**Description**
Provide a converter convert from normal numbers to Roman Numerals
[Kata-Roman Numerals](https://codingdojo.org/kata/RomanNumerals/)

The largest input for this case should be 3999

Roman rules
http://www.novaroma.org/via_romana/numbers.html

     1 --> I
     10 --> X
     7 --> VII
     31 --> XXXI

Tests
```
Given one parameter (int)
When input is 1
Expect "I" return

When input is 10
Expect "X" return

When input is 7
Expect "VII" return

When input is 31
Expect "XXXI" return

```
**Additional context**

Add any other context, links references or screenshots about the feature request here.

**Important Checklist**
- [ ] I have written unit test first, make it red(fail first).
- [ ] I have then written logic code, make it green(success)
- [ ] I have tried to refactor my code, make it understandable(document my code)

**Comment by A-Annan** [comment]
Could you assign it to me

**Comment by fengyuanyang** [comment]
Sure, assigned

**Comment by fengyuanyang** [comment]
Just update some typos and 1 test

**Comment by A-Annan** [comment]
The largest number we can write in Roman numerals is 3,999 which is MMMCMXCIX?

**Comment by A-Annan** [comment]
> The largest number we can write in Roman numerals is 3,999 which is MMMCMXCIX?

@fengyuanyang ?

**Comment by fengyuanyang** [comment]
HI @A-Annan 
yes, for this test case, we can just define the largest number is 3999.

And, that' right , 3999 is MMMCMXCIX
https://www.rapidtables.com/convert/number/roman-numerals-converter.html?x1=&x2=3999

**Comment by A-Annan** [comment]
@fengyuanyang could you add the hacktoberfest-accepted tag to this issue
