### ISSUE TITLE
[TDD] Kata - String Calculator

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#74]
**Description**
Provide a string as parameter, return a string after calculating by calculator.
[Kata-String Calculator](https://codingdojo.org/kata/StringCalculator/)

The method can take 0, 1 or 2 numbers separated by any separators defined, and returns their sum.
An empty string will return “0”.

**pattern of input "//[delimiter]\n[numbers]"**

original test
```
"//;\n1;2" should return "3"
"//|\n1|2|3" should return "6"
"//sep\n2sep3" should return "5"
"//|\n1|2,3" is invalid and should return the message "'|' expected but ',' found at position 3."

```

Tests
```
Given one parameter (string )
When input is "//;\n1;2"
Expect 3 return (delimiter is ";", result = 1 + 2) 

When input is "//|\n1|2|3"
Expect 6 return (delimiter is "|", result = 1 + 2 + 3)

When input is "//sep\n2sep3"
Expect 5 return (delimiter is "sep", result = 2 + 3)

When input is ""//|\n1|2,3"
Expect throw illegalArgumentException

```
**Additional context**

Add any other context, links references or screenshots about the feature request here.

**Important Checklist**
- [ ] I have written unit test first, make it red(fail first).
- [ ] I have then written logic code, make it green(success)
- [ ] I have tried to refactor my code, make it understandable(document my code)

**Comment by kwong21** [comment]
Hi @fengyuanyang ,

I can take this issue. May I have this assigned to me?

Thanks!

**Comment by fengyuanyang** [comment]
hi @kwong21 , sure

**Comment by kwong21** [comment]
PR for issue - #84

**Comment by fengyuanyang** [comment]
Hi @kwong21 
I have left some comments on you PR, do you still want to proceed on this.?

**Comment by kwong21** [comment]
Hey @fengyuanyang ,

Yes, of course! 
I am looking at the PR but I don't see any comments on PR #84

**Comment by fengyuanyang** [comment]
https://github.com/fengyuanyang/JavaTDD/pull/84
can you see any of my comments here ?

**Comment by kwong21** [comment]
> Hi @kwong21
> #84
> can you see any of my comments here ?

Yes I can see your comments here
