### ISSUE TITLE
[TDD] Kata - RPN Calculator

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#75]
**Description**
[RPN](https://en.wikipedia.org/wiki/Reverse_Polish_notation)(Reverse Polish Notation )

Provide a RPN Calculator (**Lets narrow to + - * /** ).
[Kata-RPN Calculator](https://codingdojo.org/kata/RPN/)

An RPN expression or postfix expression is one of the following :
- a number X, in wich case the value of the expression is that of X,
- a sequence of form E1 E2 OP where E1 and E2 are RPN expressions and OP is an arithmetic operation.

```
20 5 /        => 20/5 = 4
4 2 + 3 -     => (4+2)-3 = 3
3 5 8 * 7 + * => ((5*8)+7)*3 = 141
```

Tests
```
Given one parameter (string )
When input is "20 5 /"
Expect 4 return

When input is "4 2 + 3 -"
Expect 3 return

When input is "3 5 8 * 7 + *"
Expect 141 return

```
**Additional context**

Add any other context, links references or screenshots about the feature request here.

**Important Checklist**
- [ ] I have written unit test first, make it red(fail first).
- [ ] I have then written logic code, make it green(success)
- [ ] I have tried to refactor my code, make it understandable(document my code)

**Comment by snjazim** [comment]
Please assign this to me.

**Comment by fengyuanyang** [comment]
Hi @snjazim , I saw you have two other issues are in progress. 
I might just leave it to others for now.

**Comment by I3han** [comment]
@fengyuanyang hey can you assign me for this

**Comment by fengyuanyang** [comment]
Hi @I3han  , sure 
asisgned

**Comment by deepharshsri** [comment]
Hey, can you assign me to this?

**Comment by sahaparamjit** [comment]
@fengyuanyang 
Please assign this to me

**Comment by fengyuanyang** [comment]
Hi @sahaparamjit 
Sure

**Comment by sahaparamjit** [comment]
@fengyuanyang 
Please review #123
