### ISSUE TITLE
[TDD] Kata - Dictionary replacer

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#77]
**Description**
A simple string replacer, replace all the strings match the Dictionary Key  with Dictionary Value.

[Kata-Dictionary Replacer](https://codingdojo.org/kata/DictionaryReplacer/)

Tests
```
Given 2 parameters (String, Dictionary)
When input is ("", empty Dictionary)
Expect empty String return

When input is (“\$temp\$“, dict [“temp”, “temporary”])
Expect “temporary” return

When input is (“\$temp\$ here comes the name \$name\$“, dict [“temp”, “temporary”][“name”, “John Doe”])
Expect “temporary here comes the name John Doe” return


```
**Additional context**

Add any other context, links references or screenshots about the feature request here.

**Important Checklist**
- [ ] I have written unit test first, make it red(fail first).
- [ ] I have then written logic code, make it green(success)
- [ ] I have tried to refactor my code, make it understandable(document my code)

**Comment by snjazim** [comment]
Please assign this to me.

**Comment by surejaviren** [comment]
**please assign this task to me**
