### ISSUE TITLE
[Concurrent] In Swimming class - CountDownLatch

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#86]
**Description**
[`CountDownLatch`](https://levelup.gitconnected.com/deep-dive-countdownlatch-in-java-d33c43f91438) in Java is a kind of synchronization mechanism 
which allows one Thread to wait for one or more Threads before starts processing.

**Question**
There is a swimming class(with x members), all of them start to swim at the same time.

Provide a **Swim** class with **start** function, so participant  can start swimming.
We don't expect they can reach the goal at the same time , but we would like to check all their status at the end just once.

Tests
```
Given one parameter (string[] names )
When input is ["a", "b", "c", "d"]
Expect four Threads start at once
And return a map contains all their status.(x.contains(input) should be all true)

```
**Additional context**

Add any other context, links references or screenshots about the feature request here.

**Important Checklist**
- [ ] I have written unit test first, make it red(fail first).
- [ ] I have then written logic code, make it green(success)
- [ ] I have tried to refactor my code, make it understandable(document my code)

**Comment by surejaviren** [comment]
**please assign this to me**

**Comment by fengyuanyang** [comment]
Sure, @surejaviren 
Thanks 👍

**Comment by fengyuanyang** [comment]
Hi @viren-sureja  are you still working on this one ?

**Comment by snjazim** [comment]
Could you assign this to me?

**Comment by viren-sureja** [comment]
> Hi @viren-sureja are you still working on this one ?

ohh sorry sir got stuck in some work.

**Comment by fengyuanyang** [comment]
Hi @viren-sureja 
I would like to unassign this issue , just leave comment if you are ready to work on this
