### ISSUE TITLE
TypeCasting and unitTests

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#9]
**Background**
It's a good start to learn some java casting.  

**How**.   
Write TypeCastingTest with unit tests, with Widening Casting and Narrowing Casting 
Implement TypeCasting class with several methods to do Widening Casting and Narrowing Casting 

**DoD**
All the unittests include all the types mentioned in [Reference ](https://www.w3schools.com/java/java_type_casting.asp)

**Comment by mcruzdev** [comment]
@fengyuanyang can I get that?

**Comment by fengyuanyang** [comment]
sure @mcruzdev 
Thanks , go head, assigned
