### ISSUE TITLE
[Algorithm] binary search

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#94]
**Description**
Provide a function that implements **binary search**
[Binary Search](https://medium.com/better-programming/three-smart-ways-to-use-binary-search-in-coding-interviews-250ba296cb82)

```
Given 2 parameters (int[] searchArray, key)
When searchArray = [1,2,3,4,5,6,7], key=5
Expect 3 return (3 steps to find 5)

When searchArray = [1,2,3,4,5,6,7,8], key=2
Expect 2 return (2 steps to find 2)


When searchArray = [1,2,3,8,5,6,7,4], key=2
Expect throw illegalArgumentException
(searchArray must be in asc order)

```
**Additional context**

Add any other context, links references or screenshots about the feature request here.

**Important Checklist**
- [ ] I have written unit test first, make it red(fail first).
- [ ] I have then written logic code, make it green(success)
- [ ] I have tried to refactor my code, make it understandable(document my code)

**Comment by Tegridy** [comment]
Hi, could you assign me please ?

**Comment by fengyuanyang** [comment]
sure @Tegridy
