### ISSUE TITLE
[Algorithm] bubble sort

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#97]
**Description**
Provide a function that implements **bubble sort**

Example:
```
First Pass:
( 5 1 4 2 8 ) –> ( 1 5 4 2 8 ), Here, algorithm compares the first two elements, and swaps since 5 > 1.
( 1 5 4 2 8 ) –>  ( 1 4 5 2 8 ), Swap since 5 > 4
( 1 4 5 2 8 ) –>  ( 1 4 2 5 8 ), Swap since 5 > 2
( 1 4 2 5 8 ) –> ( 1 4 2 5 8 ), Now, since these elements are already in order (8 > 5), algorithm does not swap them.

Second Pass:
( 1 4 2 5 8 ) –> ( 1 4 2 5 8 )
( 1 4 2 5 8 ) –> ( 1 2 4 5 8 ), Swap since 4 > 2
( 1 2 4 5 8 ) –> ( 1 2 4 5 8 )
( 1 2 4 5 8 ) –>  ( 1 2 4 5 8 )
Now, the array is already sorted, but our algorithm does not know if it is completed. The algorithm needs one whole pass without any swap to know it is sorted.

Third Pass:
( 1 2 4 5 8 ) –> ( 1 2 4 5 8 )
( 1 2 4 5 8 ) –> ( 1 2 4 5 8 )
( 1 2 4 5 8 ) –> ( 1 2 4 5 8 )
( 1 2 4 5 8 ) –> ( 1 2 4 5 8 )
```

```
Given 1 parameters (int[] array)
When array = [5, 1, 4, 2, 8 ]
Expect [1, 2, 4, 5, 8 ] return

When array = [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
Expect [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] return
```
**Additional context**

Add any other context, links references or screenshots about the feature request here.

**Important Checklist**
- [ ] I have written unit test first, make it red(fail first).
- [ ] I have then written logic code, make it green(success)
- [ ] I have tried to refactor my code, make it understandable(document my code)

**Comment by snjazim** [comment]
I'm very interested to work on this issue. Please assign this to me.

**Comment by manavbhikadiya** [comment]
please assign this task to me. I have the good knowledge about the sorting and searching algorithms..

**Comment by snjazim** [comment]
Please can you review my PR @fengyuanyang

**Comment by snjazim** [comment]
I have resolved the comment you have in the PR. 
Please review my PR.
