### ISSUE TITLE
[Algorithm] Linear Search

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#98]
**Description**
Provide a function that implements **Liner Search**

Example:
```
( {10, 20, 80, 30, 60, 50, 110, 100, 130, 170}, 110) -> 6
( {10, 20, 80, 30, 60, 50, 110, 100, 130, 170}, 175) -> -1
```

```
Given 2 parameters for function(int[] array, int searchNumber)
When array = {10, 20, 80, 30, 60, 50, 110, 100, 130, 170}, and searchNumber = 110
Expect 6 return

When array = {10, 20, 80, 30, 60, 50, 110, 100, 130, 170}, and searchNumber = 175
Expect -1 return
```
**Additional context**

Add any other context, links references or screenshots about the feature request here.

**Important Checklist**
- [ ] I have written unit test first, make it red(fail first).
- [ ] I have then written logic code, make it green(success)
- [ ] I have tried to refactor my code, make it understandable(document my code)

**Comment by mansiwagh05** [comment]
Hi @fengyuanyang can I work on this?

**Comment by fengyuanyang** [comment]
sure, @mansiwagh05

**Comment by manavbhikadiya** [comment]
i have the solution of the linear search problem to find out the particular key element from it. please assign this task to me..

**Comment by irohitsatya** [comment]
@fengyuanyang can I raise a PR for this?
