### ISSUE TITLE
Find the Missing Number

### ISSUE THREAD

**Issue by fengyuanyang** [fengyuanyang/JavaTDD#99]
**Description**

Provide a function to find a missing number, these numbers(integer) are in the range of 1 to n.

**Approach** 
The length of the array is n-1. So the sum of all n elements, i.e sum of numbers from 1 to n can be calculated using the formula n*(n+1)/2. Now find the sum of all the elements in the array and subtract it from the sum of first n natural numbers, it will be the value of the missing element.

example
```
{1, 2, 4, 6, 3, 7, 8} -> 5 is missing
{1, 2, 3, 5} -> 4 is missing
```

```
Given 1 parameters (int array)
When array = {1, 2, 4, 6, 3, 7, 8}
Expect 5 return

When array = {1, 2, 3, 5}
Expect 4 return
```
**Additional context**

Add any other context, links references or screenshots about the feature request here.

**Important Checklist**
- [ ] I have written unit test first, make it red(fail first).
- [ ] I have then written logic code, make it green(success)
- [ ] I have tried to refactor my code, make it understandable(document my code)

**Comment by Manasa1013** [comment]
Hey!I am working on this, can you assign it to me?

**Comment by fengyuanyang** [comment]
sure @Manasa1013

**Comment by apri44** [comment]
you'll have to be assigned to some issue before working on it?

**Comment by fengyuanyang** [comment]
Hi @apri44 
you are welcome to work on any issues , just let me know you are working on it . 
Then I will add you as assignees.

**Comment by audy910** [comment]
Hi! I would like to work on this as well, if possible.

**Comment by fengyuanyang** [comment]
Sure 
go ahead

**Comment by Yasas4D** [comment]
Hi, as no one completed this, I implemented the function
Please take the pull request
Thank you
